# Generated by Django 3.1.4 on 2020-12-26 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DumpModel',
            fields=[
                ('contents_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('contents_name', models.CharField(max_length=50)),
                ('region', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('category', models.CharField(max_length=20)),
                ('price', models.IntegerField()),
                ('start_dtm', models.DateTimeField()),
                ('end_dtm', models.DateTimeField()),
                ('register_dtm', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'tb__dump',
            },
        ),
    ]
